
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 25.0.1703.6
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Dockerfile", "Dockerfile\Dockerfile.csproj", "{39E76BEF-FA24-4B7F-AE9E-12CFBD94953A}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{39E76BEF-FA24-4B7F-AE9E-12CFBD94953A}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{39E76BEF-FA24-4B7F-AE9E-12CFBD94953A}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{39E76BEF-FA24-4B7F-AE9E-12CFBD94953A}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{39E76BEF-FA24-4B7F-AE9E-12CFBD94953A}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {66D35D8A-5F09-4086-8DF7-5A159F04639A}
	EndGlobalSection
EndGlobal
